### ISSUE TITLE
Semantic markup

### ISSUE THREAD

**Issue by ghost** [mateufel/ColmarAcademy#2]
https://github.com/mateufel/ColmarAcademy/blob/master/index.html#L14-L56

Nice job using HTML5 tags like `header`, `nav`, `main`, `section` and `footer` to make your markup more semantic 👍 

Consider adding some more semantic tags like: `article`, `aside`, `figure`, etc. This is much better than relying constantly on `div` tags, and can make your code much easier to read and reason about.

**Comment by mateufel** [comment]
Thanks 👍 I will read up further on those tags.
