### ISSUE TITLE
`img alt`

### ISSUE THREAD

**Issue by ghost** [mateufel/ColmarAcademy#4]
https://github.com/mateufel/ColmarAcademy/blob/master/index.html#L60-L71

Give your `img` tags an `alt` attribute with a value that actually describes the image, just in case your website is not able to load it. Do not leave this value blank unless you are sure the image is insignificant to the user experience.

Doing so will help improve the accessibility of your website, which might be accessed by visually impaired users on e-readers or other devices that might deliberately neglect images-- as well as any other time that your website is just unable to render images.

**Comment by mateufel** [comment]
Ok, thanks for your suggestion. I let them empty because I felt that their description would have been duplicated by the underlying title and paragraph. Maybe this is wasn't true for all images, though.
